allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
minimumReleaseAgeExclude:
  - "@i18n-micro/core@1.3.17"
  - "@i18n-micro/hmr@1.0.14"
  - "@i18n-micro/path-strategy@1.3.16"
  - "@i18n-micro/route-strategy@1.1.24"
  - "@i18n-micro/test-utils@1.2.14"
  - "@i18n-micro/types@1.2.14"
  - "@i18n-micro/utils@1.0.22"
  - nuxt-i18n-micro@3.29.2
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
